Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

AllCops:
  SuggestExtensions: false

Naming/MethodParameterName:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
